Update report_einvoice.xml
odoo-ecuador/odoo-ecuador pull request #227
Opened 2018-06-13 21:25 UTC by DianaLS

reporte factura electronica

2018-06-18 16:52 UTC, jomiceve approved these changes

2018-06-18 18:38 UTC, ovnicraft requested changes
Confirmar porque eliminamos el codigo de barras de la clave de acceso.

2018-06-18 18:38 UTC, ovnicraft commented on l10n_ec_einvoice/views/report_einvoice.xml
> +                                    <span t-esc="o.clave_acceso"/><br/>
eliminamos la generacion del codigo de barras ?

2018-06-18 20:01 UTC, DianaLS commented
No imprime imagen en pdf por eso se eliminó y se imprime solo valor por el momento, hasta resolver    En lunes, 18 de junio de 2018 13:38:03 GMT-5, Cristian  Salamea <notifications@github.com> escribió:  
 
 
@ovnicraft requested changes on this pull request.

Confirmar porque eliminamos el codigo de barras de la clave de acceso.

In l10n_ec_einvoice/views/report_einvoice.xml:
>                                      <span><strong>FECHA Y HORA DE AUTORIZACION: </strong></span><span t-esc="o.fecha_autorizacion"/><br/>
                                     <span><strong>AMBIENTE: </strong></span><span t-esc="res_company.env_service == '1' and 'PRUEBAS' or 'PRODUCCION'"/><br/>
                                     <span><strong>EMISION: </strong><span t-esc="res_company.emission_code == '1' and 'NORMAL' or 'INDISPONIBILIDAD'"/></span><br/>
                                     <span><strong>CLAVE DE ACCESO</strong></span><br/>
-                                    <div class="text-align: left;">
-                                        <img style="text-align: left;" t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s&amp;humanreadable=1' % ('Code128', o.clave_acceso, 450, 60)"/>
-                                    </div><br/>
+                                    <span t-esc="o.clave_acceso"/><br/>

eliminamos la generacion del codigo de barras ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   
 
|  | Libre de virus. www.avast.com  |

2018-06-20 14:47 UTC, ovnicraft commented
@DianaLS ha revisado por que no imprime ? no podemos eliminar algo requerido.
Puedes abrir un issue con el error que indicas de no impresión del código de barras.

2018-06-20 14:47 UTC, closed without merging

2018-06-22 14:32 UTC, DianaLS commented
Ya esta reportado el problema es con las fuentesCan't setFont(Times-Roman) missing the T1 files?

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Can't setFont(Times-Roman) missing the T1 files?

I have the error : Can't find .pfb for face 'Times-Roman' Error: reportlab.graphics.renderPM.RenderPMError: Ca...
 |

 |

 |



 

    En miércoles, 20 de junio de 2018 9:47:36 GMT-5, Cristian Salamea <notifications@github.com> escribió:  
 
 
@DianaLS ha revisado por que no imprime ? no podemos eliminar algo requerido.
Puedes abrir un issue con el error que indicas de no impresión del código de barras.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
   
 
|  | Libre de virus. www.avast.com  |